# Generated by Django 3.2.25 on 2025-08-14 08:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='folder', max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('icon', models.CharField(default='desktop', max_length=50)),
                ('icon_color', models.CharField(default='#10b981', max_length=7)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='online', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_external', models.BooleanField(default=False)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('authenticated', 'Authenticated'), ('admin', 'Admin')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='portal.portalsection')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Enterprise Systems Portal', max_length=100)),
                ('site_title_en', models.CharField(default='Enterprise Systems Portal', max_length=100)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='portal/logos/')),
                ('theme_color', models.CharField(default='#6366f1', max_length=7)),
                ('background_color', models.CharField(default='#f8fafc', max_length=7)),
                ('show_status_indicators', models.BooleanField(default=True)),
                ('enable_animations', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True)),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS styles')),
                ('custom_js', models.TextField(blank=True, help_text='Custom JavaScript')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portal Settings',
                'verbose_name_plural': 'Portal Settings',
            },
        ),
        migrations.CreateModel(
            name='PortalAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='portal.systemcard')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='FactoryButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('icon', models.CharField(default='link', max_length=50)),
                ('background_color', models.CharField(default='#3b82f6', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('authenticated', 'Authenticated'), ('admin', 'Admin')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
