# Generated by Django 3.2.25 on 2025-08-15 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalsection',
            name='factory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_factory', to='portal.factorybutton'),
        ),
    ]
