# Generated by Django 3.2.25 on 2025-08-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_portalsection_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorybutton',
            name='description_vi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='factorybutton',
            name='description_zh_hans',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='factorybutton',
            name='description_zh_hant',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='factorybutton',
            name='name_vi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='factorybutton',
            name='name_zh_hans',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='factorybutton',
            name='name_zh_hant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portalsection',
            name='description_vi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portalsection',
            name='description_zh_hans',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portalsection',
            name='description_zh_hant',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portalsection',
            name='name_vi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portalsection',
            name='name_zh_hans',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portalsection',
            name='name_zh_hant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='systemcard',
            name='description_vi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='systemcard',
            name='description_zh_hans',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='systemcard',
            name='description_zh_hant',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='systemcard',
            name='name_vi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='systemcard',
            name='name_zh_hans',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='systemcard',
            name='name_zh_hant',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
