# Generated by Django 3.2.25 on 2025-08-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20250816_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorybutton',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='portalsection',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='systemcard',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
