# Generated by Django 3.2.25 on 2025-08-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20250816_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalsettings',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='background/'),
        ),
        migrations.AddField(
            model_name='portalsettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicon/'),
        ),
        migrations.AddField(
            model_name='portalsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
